language: android

android:
    components:
        - tools
        - build-tools-24.0.1
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

jdk:
    - oraclejdk8
    
deploy:
    provider: release
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
    repo: Deepankar-promact/CalculatorApp
    tags: true
script:
- ./gradlew build