{
  "language": "android",
  "jdk": "oraclejdk7",
  "android": {
    "components": [
      "tools",
      "build-tools-22.0.0",
      "android-21",
      "extra-google-google_play_services",
      "extra-google-m2repository",
      "extra-android-m2repository",
      "addon-google_apis-google-19"
    ]
  },
  "after_success": [
    "chmod +x ./upload-apk.sh",
    "./upload-apk.sh"
  ],
  "script": "./gradlew build assembleRelease",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}